name: Vercel Production Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build_test_and_deploy:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          npm install

      - name: Run unit tests
        run: npm test

      - name: Run e2e tests
        run: npm run test:e2e
        env:
          JWT_SECRET: ${{ 'oSYi2StE3vmYUQky' }}
          NODE_ENV: test

      - name: Install Vercel CLI
        working-directory: .
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        working-directory: .
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        working-directory: .
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }} ./backend

      - name: Deploy Project Artifacts to Vercel
        working-directory: .
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
  trigger-event:
    runs-on: ubuntu-latest
    needs: build_test_and_deploy
    steps:
      - name: Fire event
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PERSONNAL_ACCESS_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/cyngu/integration-continue-exo-react/dispatches \
            -d '{"event_type":"dispatch-event"}'